<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ghtk\Event' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/ghtk/Event.php';

return $this->services['Plugin\ghtk\Event'] = new \Plugin\ghtk\Event(${($_ = isset($this->services['Plugin\ghtk\Repository\ConfigRepository']) ? $this->services['Plugin\ghtk\Repository\ConfigRepository'] : $this->load('getConfigRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Plugin\ghtk\Service\GhtkApi']) ? $this->services['Plugin\ghtk\Service\GhtkApi'] : $this->load('getGhtkApiService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\Repository\BaseInfoRepository']) ? $this->services['Eccube\Repository\BaseInfoRepository'] : $this->getBaseInfoRepositoryService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\Repository\Master\PrefRepository']) ? $this->services['Eccube\Repository\Master\PrefRepository'] : $this->load('getPrefRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\Common\EccubeConfig']) ? $this->services['Eccube\Common\EccubeConfig'] : ($this->services['Eccube\Common\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'}, ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->getDoctrine_Orm_DefaultEntityManagerService()) && false ?: '_'}, ${($_ = isset($this->services['Eccube\Repository\Master\OrderStatusRepository']) ? $this->services['Eccube\Repository\Master\OrderStatusRepository'] : $this->load('getOrderStatusRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'});
