<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ghtk\Form\Type\Admin\GHTKProductType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Eccube/Form/Type/Admin/ProductType.php';
include_once $this->targetDirs[3].'/app/Plugin/ghtk/Form/Type/Admin/GHTKProductType.php';

return $this->services['Plugin\ghtk\Form\Type\Admin\GHTKProductType'] = new \Plugin\ghtk\Form\Type\Admin\GHTKProductType(${($_ = isset($this->services['Eccube\Repository\CategoryRepository']) ? $this->services['Eccube\Repository\CategoryRepository'] : $this->load('getCategoryRepositoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['Eccube\Common\EccubeConfig']) ? $this->services['Eccube\Common\EccubeConfig'] : ($this->services['Eccube\Common\EccubeConfig'] = new \Eccube\Common\EccubeConfig($this))) && false ?: '_'});
