<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ghtk\Repository\GhtkOrderStatusRepository' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/ghtk/Repository/GhtkOrderStatusRepository.php';

return $this->services['Plugin\ghtk\Repository\GhtkOrderStatusRepository'] = new \Plugin\ghtk\Repository\GhtkOrderStatusRepository(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});
