<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYncndob\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYncndob/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYncndob.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\ContainerYncndob\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \ContainerYncndob\EccubeProdProjectContainer([
    'container.build_hash' => 'Yncndob',
    'container.build_id' => '1b0e606b',
    'container.build_time' => 1636191985,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYncndob');
