<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\ghtk\Service\GhtkApi' shared autowired service.

include_once $this->targetDirs[3].'/app/Plugin/ghtk/Service/GhtkApi.php';

return $this->services['Plugin\ghtk\Service\GhtkApi'] = new \Plugin\ghtk\Service\GhtkApi(${($_ = isset($this->services['Plugin\ghtk\Repository\ConfigRepository']) ? $this->services['Plugin\ghtk\Repository\ConfigRepository'] : $this->load('getConfigRepositoryService.php')) && false ?: '_'});
